# To create the conda environment, run:
#   conda env create -f environment.yml
name: upvote-predictor
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.13.3
  - pytorch=2.6
  - torchvision=0.21.0
  - psycopg=3.2.6
  - scikit-learn=1.6.1
  - fastapi=0.112.2
  - uvicorn=0.32.1
  - pydantic-settings=2.8.1
  - pytest=8.3.4
  - pandas=2.2.3
  - matplotlib=3.10.0
  - seaborn=0.13.2
